// FOR LOGIN PAGE
export const SEND_DATA_TO_LOGIN = 'SEND_DATA_TO_LOGIN'

// FOR REGISTER PAGE
export const SEND_DATA_TO_REGISTER = 'SEND_DATA_TO_REGISTER'

// FOR CREATEAUCTION PAGE
export const SEND_DATA_TO_CREATE_AUCTION = 'SEND_DATA_TO_CREATE_AUCTION'

// FOR AUCTIONS LIST
export const LOAD_AUCTIONS = 'LOAD_AUCTIONS'
export const LOAD_AUCTION_BY_ID = 'LOAD_AUCTION_BY_ID'
